title: "Lance Pioch"
description: "Lance Pioch is a very experienced developer and programmer."
keywords: ["lance", "pioch", "programmer", "developer", "entrepreneur"]

url: /
destination: public

permalink: "posts/:title.html"

# RSS feed
feed:
    max_item: 25

# Facebook Open Graph
open_graph:
    locale: en_US

exclude: ['readme.md', 'LICENSE', 'composer.json', 'composer.lock', 'public']